// Auto-generated by Feather Bot
const collectionsData = {
  "Mining": [
    {
      "name": "Cobblestone",
      "image": "assets/mining/Cobblestone_JE5_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "Blue_cat1745",
          "score": "125.0M+"
        },
        {
          "rank": 2,
          "name": "Unknown",
          "score": "122.0M+"
        },
        {
          "rank": 3,
          "name": "UbeRNooB8834",
          "score": "115.0M+"
        },
        {
          "rank": 4,
          "name": "SphinxWraith",
          "score": "107.0M+"
        },
        {
          "rank": 5,
          "name": "Moerderfisch",
          "score": "59.5M+"
        },
        {
          "rank": 6,
          "name": "ieduoo",
          "score": "40.9M+"
        },
        {
          "rank": 7,
          "name": "NetworkPg",
          "score": "5.8M+"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Iron Ingot",
      "image": "assets/mining/Iron_Ingot_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "weball22604",
          "score": "45.5M+"
        },
        {
          "rank": 2,
          "name": "ZepthyrX",
          "score": "29.5M+"
        },
        {
          "rank": 3,
          "name": "Exnned",
          "score": "16.0M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "668.4K+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "15.1K+"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Emircanyilmaz",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Gold Ingot",
      "image": "assets/mining/Gold_Ingot_JE4_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "AndroidPARAS",
          "score": "50.9M+"
        },
        {
          "rank": 2,
          "name": "Meetgamer76",
          "score": "50.0M+"
        },
        {
          "rank": 3,
          "name": "Exnned",
          "score": "28.0M+"
        },
        {
          "rank": 4,
          "name": "Shubh_gamer9497",
          "score": "17.0M+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "9.7M+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "677.0K+"
        },
        {
          "rank": 7,
          "name": "Jrian8733",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "SphinxWraith",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Himmu9186",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "uatitan580",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Diamond",
      "image": "assets/mining/Diamond_JE3_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "HeGzoStRqFe",
          "score": "35.9M+"
        },
        {
          "rank": 2,
          "name": "Ashish0809",
          "score": "33.0M+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "9.6M+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "5.8M+"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Emerald",
      "image": "assets/mining/Emerald_JE3_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "LORDXGASTER1508",
          "score": "15.2M+"
        },
        {
          "rank": 2,
          "name": "NetworkPg",
          "score": "222.1K+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "2.9K+"
        },
        {
          "rank": 4,
          "name": "Senpaiyusuf",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Fearstruck8500",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Redstone",
      "image": "assets/mining/Redstone_Dust_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "Rehan2038",
          "score": "97.1M+"
        },
        {
          "rank": 2,
          "name": "Firegod174",
          "score": "80.0M+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "54.2M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "2.2M+"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Coal",
      "image": "assets/mining/Coal_JE4_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "HeGzoStRqFe",
          "score": "179.9M+"
        },
        {
          "rank": 2,
          "name": "C4P2L",
          "score": "96.8M+"
        },
        {
          "rank": 3,
          "name": "aPumpkinGod2",
          "score": "46.0M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "3.4M+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "16.5K+"
        },
        {
          "rank": 6,
          "name": "KaosTheChaos",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Burakbu001",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "HeGzoStRqFe",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Lapis Lazuli",
      "image": "assets/mining/Lapis_Lazuli_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "DevilGamer07755",
          "score": "N/A"
        },
        {
          "rank": 2,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 3,
          "name": "PotatoPlayer922",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Obsidian",
      "image": "assets/mining/Obsidian_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "ENTITY_3038628",
          "score": "32.7M+"
        },
        {
          "rank": 2,
          "name": "Ivyman1992",
          "score": "1.0M+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "85.8K+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "29.8K+"
        },
        {
          "rank": 5,
          "name": "Icezane5011",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Ice",
      "image": "assets/mining/Ice_JE2_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "SquareSquid8492",
          "score": "162.6M+"
        },
        {
          "rank": 2,
          "name": "ieduoo",
          "score": "281.6K+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "233.7K+"
        },
        {
          "rank": 4,
          "name": "KaosTheChaos",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Copingo",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "End Stone",
      "image": "img/End_Stone.png",
      "players": [
        {
          "rank": 1,
          "name": "ieduoo",
          "score": "128.7K+"
        },
        {
          "rank": 2,
          "name": "NetworkPg",
          "score": "14.5K+"
        },
        {
          "rank": 3,
          "name": "ItIsYeElk69",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    }
  ],
  "Farming": [
    {
      "name": "Wheat",
      "image": "assets/farming/Wheat_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "Naitikwarior",
          "score": "42.4M+"
        },
        {
          "rank": 2,
          "name": "Manglubaba",
          "score": "28.2M+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "1.1M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "23.0K+"
        },
        {
          "rank": 5,
          "name": "Troubles2Go",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "PriestlyPath870",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Hefty6248",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "TINKUGAMER1232",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Carrot",
      "image": "assets/farming/Carrot_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "AK_GAMERR5398",
          "score": "65.0M+"
        },
        {
          "rank": 2,
          "name": "HeGzoStRqFe",
          "score": "45.6M+"
        },
        {
          "rank": 3,
          "name": "Gelacktic",
          "score": "45.0M+"
        },
        {
          "rank": 4,
          "name": "C4P2L",
          "score": "13.0M+"
        },
        {
          "rank": 5,
          "name": "NetworkPg",
          "score": "16.5K+"
        },
        {
          "rank": 6,
          "name": "ieduoo",
          "score": "3.6K+"
        },
        {
          "rank": 7,
          "name": "AndyGamer024",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Potato",
      "image": "assets/farming/Potato_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "Ashish0809",
          "score": "413.0M+"
        },
        {
          "rank": 2,
          "name": "Swagmire2329",
          "score": "255.0M+"
        },
        {
          "rank": 3,
          "name": "DesiringSugar39",
          "score": "220.0M+"
        },
        {
          "rank": 4,
          "name": "TXLEGEND111",
          "score": "210.0M+"
        },
        {
          "rank": 5,
          "name": "NetworkPg",
          "score": "434.6K+"
        },
        {
          "rank": 6,
          "name": "ieduoo",
          "score": "130.4K+"
        },
        {
          "rank": 7,
          "name": "Gamer_legend746",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Pumpkin",
      "image": "assets/farming/150px-Carved_Pumpkin_(N)_JE5.png",
      "players": [
        {
          "rank": 1,
          "name": "Classyisreal",
          "score": "106.9M+"
        },
        {
          "rank": 2,
          "name": "Madstar118YT",
          "score": "100.0M+"
        },
        {
          "rank": 3,
          "name": "HeGzoStRqFe",
          "score": "48.3M+"
        },
        {
          "rank": 4,
          "name": "AndyGamer024",
          "score": "28.4M+"
        },
        {
          "rank": 5,
          "name": "NetworkPg",
          "score": "100.0K+"
        },
        {
          "rank": 6,
          "name": "ieduoo",
          "score": "80.3K+"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "aPumpkinGod2",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "GMG_games",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Parmeseanpud",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Melon",
      "image": "assets/farming/Melon_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "MrTheAyu",
          "score": "400.0M+"
        },
        {
          "rank": 2,
          "name": "Jeremy2075",
          "score": "171.0M+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "50.1M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "255.7K+"
        },
        {
          "rank": 5,
          "name": "HeGzoStRqFe",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Lenny1sCo0l",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Mrbase101",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "RanuTheAxo",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Seed",
      "image": "assets/farming/Wheat_Seeds_JE1_BE1.png",
      "players": [
        {
          "rank": 1,
          "name": "Troubles2Go",
          "score": "N/A"
        },
        {
          "rank": 2,
          "name": "PriestlyPath870",
          "score": "N/A"
        },
        {
          "rank": 3,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "GRAVITY8303",
          "score": "12.1M+"
        },
        {
          "rank": 7,
          "name": "TINKUGAMER1232",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Araaflatif",
          "score": "10.4M+"
        },
        {
          "rank": 10,
          "name": "JODHEMANT8975",
          "score": "2M+"
        }
      ]
    },
    {
      "name": "Beetroot",
      "image": "assets/farming/Beetroot_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "Creepyshorts",
          "score": "123.2M+"
        },
        {
          "rank": 2,
          "name": "club32",
          "score": "45.3M+"
        },
        {
          "rank": 3,
          "name": "HeGzoStRqFe",
          "score": "45.0M+"
        },
        {
          "rank": 4,
          "name": "Tonykiller7895",
          "score": "41.0M+"
        },
        {
          "rank": 5,
          "name": "Perry3338",
          "score": "32.0M+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "314.1K+"
        },
        {
          "rank": 7,
          "name": "ieduoo",
          "score": "37.0K+"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Mushroom",
      "image": "assets/farming/Mushroom.gif",
      "players": [
        {
          "rank": 1,
          "name": "WujuCake",
          "score": "17.0M+"
        },
        {
          "rank": 2,
          "name": "ieduoo",
          "score": "523.9K+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "39.3K+"
        },
        {
          "rank": 4,
          "name": "AndyGamer024",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Cocoa Beans",
      "image": "assets/farming/Cocoa_Beans_JE4_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "Hefty6248",
          "score": "1B+"
        },
        {
          "rank": 2,
          "name": "GRAVITY8303",
          "score": "N/A"
        },
        {
          "rank": 3,
          "name": "GlumnorbG",
          "score": "155M+"
        },
        {
          "rank": 4,
          "name": "GPK4",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "SphinxWraith",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Moerderfisch",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "SpiralCard90164",
          "score": "130.7M+"
        },
        {
          "rank": 9,
          "name": "John9678",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "AndyGamer024",
          "score": "102.3M+"
        }
      ]
    },
    {
      "name": "Cactus",
      "image": "assets/farming/Cactus_BE4.png",
      "players": [
        {
          "rank": 1,
          "name": "Aryaan045",
          "score": "100.0M+"
        },
        {
          "rank": 2,
          "name": "Kg_lcky_01",
          "score": "53.6M+"
        },
        {
          "rank": 3,
          "name": "Moerderfisch",
          "score": "51.6M+"
        },
        {
          "rank": 4,
          "name": "club32",
          "score": "43.0M+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "6.9M+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "347"
        },
        {
          "rank": 7,
          "name": "KaosTheChaos",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Hefty6248",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "TRIGUN2212",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "JODHEMANT8975",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Sugar Cane",
      "image": "assets/farming/Sugar_Cane_29_JE3_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "Luv_bats007",
          "score": "300.2M+"
        },
        {
          "rank": 2,
          "name": "ThENoOb1737",
          "score": "200.0M+"
        },
        {
          "rank": 3,
          "name": "TopsideMender34",
          "score": "101.5M+"
        },
        {
          "rank": 4,
          "name": "Perry3338",
          "score": "93.2M+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "32.2M+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "115.6K+"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Feather",
      "image": "assets/farming/Feather_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "SammyMishu",
          "score": "41.6M+"
        },
        {
          "rank": 2,
          "name": "The_Winchi",
          "score": "40.5M+"
        },
        {
          "rank": 3,
          "name": "Krar23456",
          "score": "2.8M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "178.8K+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "54.2K+"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Leather",
      "image": "assets/farming/Leather_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "sagnikisawesome",
          "score": "10.0M+"
        },
        {
          "rank": 2,
          "name": "AweomedudeW10",
          "score": "4.0M+"
        },
        {
          "rank": 3,
          "name": "Krar23456",
          "score": "2.5M+"
        },
        {
          "rank": 4,
          "name": "Ivyman1992",
          "score": "1.0M+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "37.9K+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "16.3K+"
        },
        {
          "rank": 7,
          "name": "Icezane5011",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Raw Porkchop",
      "image": "assets/farming/Raw_Porkchop_JE3_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "sboi146433",
          "score": "47.1M+"
        },
        {
          "rank": 2,
          "name": "Sky691485",
          "score": "21.6M+"
        },
        {
          "rank": 3,
          "name": "Sky691485",
          "score": "15.8M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "839.1K+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "87.8K+"
        },
        {
          "rank": 6,
          "name": "BabiestOlive47",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "NINTIN7238",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "lunarglow4820",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Raw Chicken",
      "image": "assets/farming/Raw_Chicken_JE3_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "ieduoo",
          "score": "54.1K+"
        },
        {
          "rank": 2,
          "name": "NetworkPg",
          "score": "125"
        },
        {
          "rank": 3,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "Hefty6248",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Bosslist3256770",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Raw Duck",
      "image": "assets/farming/Raw_Duck.png",
      "players": [
        {
          "rank": 1,
          "name": "SammyMishu",
          "score": "42.3M+"
        },
        {
          "rank": 2,
          "name": "The_Winchi",
          "score": "40.6M+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "164.6K+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "197"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Mutton",
      "image": "assets/farming/Raw_Mutton_new.png",
      "players": [
        {
          "rank": 1,
          "name": "ieduoo",
          "score": "38.6K+"
        },
        {
          "rank": 2,
          "name": "NetworkPg",
          "score": "21.4K+"
        },
        {
          "rank": 3,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Meetgamer76",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Raw Rabbit",
      "image": "assets/farming/Raw_Rabbit_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "RadThunder21",
          "score": "N/A"
        },
        {
          "rank": 2,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 3,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "AK_GAMERR5398",
          "score": "13.6M+"
        },
        {
          "rank": 6,
          "name": "Moerderfisch",
          "score": "6.3M+"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Fatbelly1802",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    }
  ],
  "Combat": [
    {
      "name": "Rotten Flesh",
      "image": "assets/combat/Rotten_Flesh_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "CrusionYT11",
          "score": "111.0M+"
        },
        {
          "rank": 2,
          "name": "HeGzoStRqFe",
          "score": "106.3M+"
        },
        {
          "rank": 3,
          "name": "Krar23456",
          "score": "63.0M+"
        },
        {
          "rank": 4,
          "name": "MuhammadKing276",
          "score": "30.0M+"
        },
        {
          "rank": 5,
          "name": "NetworkPg",
          "score": "3.8M+"
        },
        {
          "rank": 6,
          "name": "ieduoo",
          "score": "66.4K+"
        },
        {
          "rank": 7,
          "name": "Bosslist3256770",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Dadabhaai",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Pranjal2389",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Neelu18100",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Bone",
      "image": "assets/combat/Bone_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "mxini",
          "score": "2.0M+"
        },
        {
          "rank": 2,
          "name": "NetworkPg",
          "score": "948.9K+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "10.8K+"
        },
        {
          "rank": 4,
          "name": "Kg_lcky_01",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "HERKUL3S",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "String",
      "image": "assets/combat/String_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "M47230",
          "score": "31.2M+"
        },
        {
          "rank": 2,
          "name": "AYUSH_BHAKTE",
          "score": "30.0M+"
        },
        {
          "rank": 3,
          "name": "MADERUCHIA07",
          "score": "28.4M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "928.8K+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "50.5K+"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "MythicalPanda30",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "MythicRen13",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Spider Eye",
      "image": "assets/combat/Spider_Eye_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "MADERUCHIA07",
          "score": "18.6M+"
        },
        {
          "rank": 2,
          "name": "NetworkPg",
          "score": "888.1K+"
        },
        {
          "rank": 3,
          "name": "ieduoo",
          "score": "35.6K+"
        },
        {
          "rank": 4,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "MythicalPanda30",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Gunpowder",
      "image": "assets/combat/Gunpowder_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "NINTIN7238",
          "score": "3.3M+"
        },
        {
          "rank": 2,
          "name": "Dipanshu_FF",
          "score": "1.8M+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "134.4K+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "56"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Slime Ball",
      "image": "assets/combat/Slimeball_JE2_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "AhmedTheGuy6100",
          "score": "193.4M+"
        },
        {
          "rank": 2,
          "name": "Unknown",
          "score": "95.0M+"
        },
        {
          "rank": 3,
          "name": "Watermark998517",
          "score": "92.1M+"
        },
        {
          "rank": 4,
          "name": "SeaborneClamp18",
          "score": "91.6M+"
        },
        {
          "rank": 5,
          "name": "JODHEMANT8975",
          "score": "77.4M+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "14.3M+"
        },
        {
          "rank": 7,
          "name": "ieduoo",
          "score": "455"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "UCHIHASHERA1",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Savage_Shrey781",
          "score": "N/A"
        }
      ]
    },
    {
      "name": " Rod",
      "image": "assets/combat/Blaze_Rod_JE1_BE1.png",
      "players": [
        {
          "rank": 1,
          "name": "Herejefferson",
          "score": "N/A"
        },
        {
          "rank": 2,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 3,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 4,
          "name": "NoviceBook91",
          "score": "N/A"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Magma Cream",
      "image": "assets/combat/Magma_Cream_JE3_BE2.png",
      "players": [
        {
          "rank": 1,
          "name": "TGJASSIYT",
          "score": "80.9M+"
        },
        {
          "rank": 2,
          "name": "TGJASSIYT (Second Profile)",
          "score": "67.0M+"
        },
        {
          "rank": 3,
          "name": "Rehan2038",
          "score": "49.4M+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "6.3M+"
        },
        {
          "rank": 5,
          "name": "NetworkPg",
          "score": "6.3M+"
        },
        {
          "rank": 6,
          "name": "Ghosthunter4233",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Fahad3382",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "BlackKeyur",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    }
  ],
  "Foraging": [
    {
      "name": "Oak Log",
      "image": "assets/foraging/Oak_Log_(UD)_JE5_BE3.png",
      "players": [
        {
          "rank": 1,
          "name": "Oak_Optic",
          "score": "111.9M+"
        },
        {
          "rank": 2,
          "name": "KaosTheChaos",
          "score": "13.5M+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "1.4M+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "1.6K+"
        },
        {
          "rank": 5,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Spruce Log",
      "image": "assets/foraging/Minecraft_items_spruce_log.png",
      "players": [
        {
          "rank": 1,
          "name": "ST4ANG3",
          "score": "51.2M+"
        },
        {
          "rank": 2,
          "name": "Devilverma2533",
          "score": "24.0M+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "32.8K+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "3.0K+"
        },
        {
          "rank": 5,
          "name": "Darkshadow52195",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "TRIGUN2212",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "BoneJ5945",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "GPK4",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "NumberOne230564",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Birch Log",
      "image": "assets/foraging/Minecraft_items_birch_log.png",
      "players": [
        {
          "rank": 1,
          "name": "BoneJ5945",
          "score": "4.0M+"
        },
        {
          "rank": 2,
          "name": "PhantomQu",
          "score": "3.0M+"
        },
        {
          "rank": 3,
          "name": "NetworkPg",
          "score": "14.0K+"
        },
        {
          "rank": 4,
          "name": "ieduoo",
          "score": "1.3K+"
        },
        {
          "rank": 5,
          "name": "NumberOne230564",
          "score": "N/A"
        },
        {
          "rank": 6,
          "name": "TRIGUN2212",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Creepyshorts",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Kg_lcky_01",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "sagnikisawesome",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Creepyshorts",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Dark Oak Log",
      "image": "assets/foraging/Minecraft_items_dark_oak_log.png",
      "players": [
        {
          "rank": 1,
          "name": "Oak_Optic",
          "score": "100.0M+"
        },
        {
          "rank": 2,
          "name": "GRAVITY8303",
          "score": "34.2M+"
        },
        {
          "rank": 3,
          "name": "HeGzoStRqFe",
          "score": "24.6M+"
        },
        {
          "rank": 4,
          "name": "Moerderfisch",
          "score": "20.0M+"
        },
        {
          "rank": 5,
          "name": "NetworkPg",
          "score": "441.9K+"
        },
        {
          "rank": 6,
          "name": "ieduoo",
          "score": "2.6K+"
        },
        {
          "rank": 7,
          "name": "Gameryash322",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "SphinxWraith",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Iceberg899",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Hefty6248",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Acacia Log",
      "image": "assets/foraging/Minecraft_items_acacia_log.png",
      "players": [
        {
          "rank": 1,
          "name": "SammyMishu",
          "score": "23.5M+"
        },
        {
          "rank": 2,
          "name": "IRONMAN1237721",
          "score": "10.1M+"
        },
        {
          "rank": 3,
          "name": "Moerderfisch",
          "score": "10.0M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "15.5K+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "71"
        },
        {
          "rank": 6,
          "name": "KaosTheChaos",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "TRIGUN2212",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "ImNdricim",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Redneck_Lineman",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "AweomedudeW10",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Jungle Log",
      "image": "assets/foraging/Minecraft_items_jungle_log.png",
      "players": [
        {
          "rank": 1,
          "name": "IRONMAN1237721",
          "score": "57.3M+"
        },
        {
          "rank": 2,
          "name": "Slayer1219978",
          "score": "40.5M+"
        },
        {
          "rank": 3,
          "name": "NumberOne230564",
          "score": "13.0M+"
        },
        {
          "rank": 4,
          "name": "NetworkPg",
          "score": "6.7K+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "853"
        },
        {
          "rank": 6,
          "name": "TRIGUN2212",
          "score": "N/A"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Herejefferson",
          "score": "N/A"
        }
      ]
    },
    {
      "name": "Bamboo",
      "image": "assets/foraging/Minecraft-Bamboo.webp",
      "players": [
        {
          "rank": 1,
          "name": "HeGzoStRqFe",
          "score": "1.0B+"
        },
        {
          "rank": 2,
          "name": "JODHEMANT8975",
          "score": "132.3M+"
        },
        {
          "rank": 3,
          "name": "Rehan2038",
          "score": "98.0M+"
        },
        {
          "rank": 4,
          "name": "HueDisNwPhn",
          "score": "69.4M+"
        },
        {
          "rank": 5,
          "name": "ieduoo",
          "score": "35.1M+"
        },
        {
          "rank": 6,
          "name": "NetworkPg",
          "score": "902.2K+"
        },
        {
          "rank": 7,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 8,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 9,
          "name": "Unknown",
          "score": "N/A"
        },
        {
          "rank": 10,
          "name": "Unknown",
          "score": "N/A"
        }
      ]
    }
  ]
};
